[project]
name = "openhtf-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openhtf>=1.6.1",
    "setuptools>=80.9.0",
    "six>=1.17.0",
]
